<?php

namespace IolaCorporation\NewsBundle\Repository;

/**
 * fileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fileRepository extends \Doctrine\ORM\EntityRepository
{
}
