<?php

namespace Ropi\CommerceBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\Types\Type;

/**
 * CommerceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommerceRepository extends EntityRepository {

    public function getCountNoValidatesCommercant() {
        return $this->createQueryBuilder("com")
                        ->select(array('COUNT(com.nom)'))
                        ->where('com.valide = :false')
                        ->setParameter('false', FALSE, Type::BOOLEAN)
                        ->getQuery()
                        ->getSingleScalarResult()
        ;
    }

}
