#!/bin/bash

git pull origin master
php app/console doctrine:database:drop --force
php app/console doctrine:database:create
php app/console doctrine:schema:update --force
php app/console doctrine:fixtures:load --append
php app/console cache:clear --env=prod
php app/console assets:install --env=prod
php app/console assetic:dump --env=prod 
php app/console braincrafted:bootstrap:install
php app/console braincrafted:bootstrap:generate
