<?php

namespace Ropi\IdentiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresseRepository extends EntityRepository
{
}
