<?php

namespace Ropi\IdentiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{


    public function findUniqueEmail(array $criteria){

        $valeur =  $criteria["valeur"];

        $rep = $this
            ->createQueryBuilder('c')
            ->select(array('c','tc'))
            ->join('c.typeContact','tc')
            ->where('c.valeur = :valeur')
            ->andWhere('tc.type = :nom')
            ->setParameter('valeur', $valeur)
            ->setParameter('nom', "Mail")
            ->getQuery()
            ->execute()
            ;

        dump($rep);

        return $rep;

    }



}
