<?php

namespace Ropi\IdentiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeAdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAdresseRepository extends EntityRepository
{
}
