<?php

namespace Ropi\IdentiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeMoyenContactRepository extends EntityRepository
{
    public function loadForInscription(){
        $request = $this->createQueryBuilder("mc")
                ->where("mc.proposeInscription = :val")
                ->orWhere("mc.obligatoire = :val")
                ->setParameter("val", true)
                ->getQuery();
                ;
        
        try{
            return $request->execute();
        } catch (Exception $ex) {
            throw new \Doctrine\DBAL\Exception\ConnectionException();
        }
    }
    
}
