ropi_identite:
    resource: "@RopiIdentiteBundle/Controller/"
    type:     annotation
    prefix:   /

ropi_test:
    resource: "@RopiTestBundle/Controller/"
    type:     annotation
    prefix:   /



ropicms:
    resource: "@RopiCMSBundle/Controller/"

ropi_authentication:
    resource: "@RopiAuthenticationBundle/Controller/"
ropi_user:
    resource: "@RopiAuthenticationBundle/Resources/config/routing.yml"
