ropi_commande:
    resource: "@RopiCommandeBundle/Controller/"
    type:     annotation
    prefix:   /

ropi_parametres:
    resource: "@RopiParametresBundle/Controller/"
    type:     annotation
    prefix:   /

ropi_commerce:
    resource: "@RopiCommerceBundle/Controller/"
ropi_identite:
    resource: "@RopiIdentiteBundle/Controller/"
    type:     annotation
    prefix:   /

ropi_test:
    resource: "@RopiTestBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


ropicms:
    resource: "@RopiCMSBundle/Controller/"

ropi_authentication:
    resource: "@RopiAuthenticationBundle/Controller/"
ropi_user:
    resource: "@RopiAuthenticationBundle/Resources/config/routing.yml"

ropi_News:
    resource: "@IolaCorporationNewsBundle/Resources/config/routing.yml"
    prefix:   /

sg_datatables_bundle:
    resource: "@SgDatatablesBundle/Controller/"
    type:     annotation
    prefix:   /sg

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"