
security:
    encoders:
        Ropi\AuthenticationBundle\Entity\IdentifiantWeb : sha512
    providers:
        database:
            entity: { class:  RopiAuthenticationBundle:IdentifiantWeb }
   
    role_hierarchy:
        ROLE_ADMIN: ROLE_CMS_CREATE
        ROLE_CMS_CREATE : ROLE_UTILISATEUR_ACTIVE
        ROLE_COMMERCANT : ROLE_USER
        ROLE_UTILISATEUR_ACTIVE : ROLE_USER:
        ROLE_USER: IS_AUTHENTICATED_ANONYMOUSLY

    
    firewalls:
       
            
        auth_area:
            
            pattern: ^/
            logout_on_user_change: true
            form_login:
                check_path:  /login_check
            logout:
                path:   /logout
                target: login
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.html /admin
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/my/cms/*, roles: ROLE_ADMIN }
        - { path: ^/admin*, roles: ROLE_ADMIN }

        - { path: ^/(login_check|my|logout), roles: IS_AUTHENTICATED_FULLY}
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }