<?php

namespace Ropi\ParametresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParametreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametreRepository extends EntityRepository
{
    
}
