<?php

namespace Ropi\ParametresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParametreConcretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametreConcretRepository extends EntityRepository
{
}
