<?php
/**
 * Created by PhpStorm.
 * User: laurent
 * Date: 2/06/17
 * Time: 17:30
 */

namespace Ropi\CommerceBundle\Datatables;


use Sg\DatatablesBundle\Datatable\Column\Column;

class NomColumn extends Column
{
    public function getOptionsTemplate()
    {
        //return 'RopiCommerceBundle:Column:column.html.twig'; // TODO: Change the autogenerated stub
        return parent::getOptionsTemplate();
    }
}