<?php

namespace Ropi\CommandeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends EntityRepository
{
    public function getAll($archive = false){

        return $this->createQueryBuilder("c")
            ->select(array("c","aq","a","s","p","li","ali","comm"))
            ->leftJoin("c.articlesQuantite","aq")
            ->leftJoin("c.statut","s")
            ->leftJoin("aq.article","a")
            ->leftJoin("c.modeDeLivraison","li")
            ->leftJoin("c.paiements","p")
            ->leftJoin("c.adresseDeLivraison","ali")
            ->leftJoin("ali.commerce","comm")
            ->orderBy("c.createdAt","DESC")
            ->where("c.archive = :archive")
            ->setParameter("archive",$archive)
            ->getQuery()
            ->execute()
            ;
    }

    /**
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getNbRopi(){
        /** @var QueryBuilder $qb */
        $qb = $this->createQueryBuilder("c");

        return$qb
            ->select("SUM(aq.quantite * a.prix)")
            ->leftJoin("c.articlesQuantite","aq")
            ->leftJoin("aq.article","a")
            ->leftJoin("c.statut","s")
            ->where("s.ordre > :ordre")
            ->setParameter("ordre",2)
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }
}
