<?php

namespace Ropi\CommandeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends EntityRepository
{
    public function getAll(){

        return $this->createQueryBuilder("c")
            ->select(array("c","aq","a","s"))
            ->leftJoin("c.articlesQuantite","aq")
            ->leftJoin("c.statut","s")
            ->leftJoin("aq.article","a")
            ->orderBy("c.createdAt","DESC")
            ->getQuery()
            ->execute()
            ;
    }
}
