<?php

namespace Ropi\CommandeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementRepository extends EntityRepository
{
}
