<?php

namespace Ropi\CMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository {

    public function getLastPosition($id) {
        
        $retour = $this->createQueryBuilder("cat")
                        ->select('count(page.titreMenu)')
                        ->join("cat.pages", "page")
                        ->where('cat.id = :id')
                        ->setParameter('id', intval($id))
                        ->getQuery()
                        ->getSingleScalarResult()
                ;
        
        return intval($retour);
        
    }

}
