<?php

namespace Ropi\CMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageDynamiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageDynamiqueRepository extends EntityRepository
{
}
