services:
    ropi.commerce_voter:
                class: Ropi\CommerceBundle\Security\CommerceVoter
                tags:
                    - { name: security.voter }
                # small performance boost
                public: false

    app.datatable.commerces:
                class: Ropi\CommerceBundle\Datatables\CommerceDatatable
                parent: sg_datatables.datatable.abstract