<?php

namespace Ropi\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutRepository extends EntityRepository
{
}
