<?php

namespace Ropi\CommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EtiquetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtiquetteRepository extends EntityRepository
{
}
